### ISSUE TITLE
Adax vs. Adam

### ISSUE THREAD

**Issue by clelouch** [thograce/C2FNet#1]
Thanks for your code.
I notice that you use the adax optimizer instead of the widely used adam optimizer. How much improvement is expected?

**Comment by thograce** [comment]
In fact, the optimizer can't determine the performance of the model. In my experiment, with some effects of random parameters, the difference between Adax and Adam is within 1%. In an accidental attempt, I found that the results using Adax was more stable. If you want to apply it to your task, you can do more experiments before making choices.

**Comment by thograce** [comment]
> Thanks for your code. I notice that you use the adax optimizer instead of the widely used adam optimizer. How much improvement is expected?

In fact, the optimizer can't determine the performance of the model. In my experiment, with some effects of random parameters, the difference between Adax and Adam is within 1%. In an accidental attempt, I found that the results using Adax was more stable. If you want to apply it to your task, you can do more experiments before making choices.

**Comment by clelouch** [comment]
Many thanks for your kind help.
