### ISSUE TITLE
eval.py

### ISSUE THREAD

**Issue by syxvision** [thograce/C2FNet#3]
Hey, Thanks for your code. But I have a little problem. Since the misc.imsave() was deactivated, I changed it to the imageio.imwrite() , but there was an error when running the eval.py.
![image](https://user-images.githubusercontent.com/80019665/165202909-ee8599c0-c949-436c-88a5-749d098a695f.png)

**Comment by thograce** [comment]
> Hey, Thanks for your code. But I have a little problem. Since the misc.imsave() was deactivated, I changed it to the imageio.imwrite() , but there was an error when running the eval.py. ![image](https://user-images.githubusercontent.com/80019665/165202909-ee8599c0-c949-436c-88a5-749d098a695f.png)

This error is usually due to an invalid path. When using imageio, please pay attention to the threshold conversion, you can use the following code to save: imageio.imwrite(save_path+name, (res*255).astype(np.uint8)). After running the MyTest.py, the testing results of the A method should be saved in the ./results/A by default. At this time, please set method="A" in eval.py. After confirming that images themselves and their paths are correct, please check several items in eval.py, such as the datasets name and GTs path.

**Comment by thograce** [comment]
> Hey, Thanks for your code. But I have a little problem. Since the misc.imsave() was deactivated, I changed it to the imageio.imwrite() , but there was an error when running the eval.py. ![image](https://user-images.githubusercontent.com/80019665/165202909-ee8599c0-c949-436c-88a5-749d098a695f.png)

**Comment by thograce** [comment]
> > Hey, Thanks for your code. But I have a little problem. Since the misc.imsave() was deactivated, I changed it to the imageio.imwrite() , but there was an error when running the eval.py. ![image](https://user-images.githubusercontent.com/80019665/165202909-ee8599c0-c949-436c-88a5-749d098a695f.png)
> 
> This error is usually due to an invalid path. When using imageio, please pay attention to the threshold conversion, you can use the following code to save: imageio.imwrite(save_path+name, (res*255).astype(np.uint8)). After running the MyTest.py, the testing results of the A method should be saved in the ./results/A by default. At this time, please set method="A" in eval.py. After confirming that images themselves and their paths are correct, please check several items in eval.py, such as the datasets name and GTs path.

Furthermore, I have specified the version of misc in requirement.txt. If you want to use misc to save pictures normally, please make sure scipy==1.2.2.

**Comment by syxvision** [comment]
Thank you very much, the problem has been solved.

**Comment by syxvision** [comment]
Really appreciated.
