### ISSUE TITLE
Resources Download Problem

### ISSUE THREAD

**Issue by Lwt-diamond** [thograce/C2FNet#7]
I want to get the resources of this project, but the resources in Google Driver of this project are very difficult to fetch in China. Could you upload the resources to **Aliyun drive** or **BaiDu Netdisk**？  I recommend you use Aliyun drive, because its speed is very fast.
P.S.：
This is the official website of Aliyu drive:
https://www.aliyundrive.com/

**Comment by thograce** [comment]
> I want to get the resources of this project, but the resources in Google Driver of this project are very difficult to fetch in China. Could you upload the resources to **Aliyun drive** or **BaiDu Netdisk**？ I recommend you use Aliyun drive, because its speed is very fast. P.S.： This is the official website of Aliyu drive: https://www.aliyundrive.com/

A collection of multiple COD methods shared by ZoomNet authors can be found in [download link (Baidu Pan)](https://pan.baidu.com/s/1dLMqa4tix1gdBN1uWrCPbQ) with Code: yxy9, including C2FNet.

**Comment by Lwt-diamond** [comment]
Thank you very much.
